### PR TITLE
CSRF Authorization Error Fix

### PR DESCRIPTION
**Pull request by MTau314**
Fixed CSRF authorization error

```
ueberauth_failure: %Ueberauth.Failure{
      errors: [
        %Ueberauth.Failure.Error{
          message: "Cross-Site Request Forgery attack",
          message_key: :csrf_attack
        }
      ],
      provider: :discord,
      strategy: Ueberauth.Strategy.Discord
    }
```

### CODE REVIEW

**Comment by schwarz** [comment]
Do you rely on ueberauth version 0.6.3? Otherwise we could upgrade to 0.7 and use the new CSRF protection helpers that were [added](https://github.com/ueberauth/ueberauth/pull/136).

Reference upgrades in other strategies:

* https://github.com/ueberauth/ueberauth_google/pull/82/files
* https://github.com/ueberauth/ueberauth_github/pull/63/files

**Comment by schwarz** [comment]
Should be handled by #14

**Comment by sergiotapia** [comment]
Hi, I'm using latest:

```
{:ueberauth, "~> 0.9.0"},
{:ueberauth_discord, "~> 0.7.0"}
```

But I'm still seeing this error. Is there something I need to set or configure so that this works and I don't get the CSRF error?

> [info] request_id=FvIecvHGJx04R6UAAGLi user_id=40020f61-71c7-491a-a3cb-dd0c84d0b676  Unable to log in. Error: %Ueberauth.Failure{errors: [%Ueberauth.Failure.Error{message: "Cross-Site Request Forgery attack", message_key: :csrf_attack}], provider: :discord, strategy: Ueberauth.Strategy.Discord}.

**Comment by schwarz** [comment]
I can't seem to reproduce this locally in [ueberauth/ueberauth_example](https://github.com/ueberauth/ueberauth_example). Are you getting this error after authorising on Discord? Does the URL include the state parameter?

**Comment by sergiotapia** [comment]
My apologies @schwarz - we were doing some shenanigans with the session that caused some collision with ueberauth. Nothing to do with your Discord strategy. 

To would be Googlers, make sure you look into what you're doing with your session before ueberauth steps in.

**Comment by schwarz** [comment]
No worries!

**Pull request closed without merging**
